CREATE OR REPLACE DATABASE assignment_1;
CREATE OR REPLACE STAGE stage_assignment 
    URL = 'azure://williamz25.blob.core.windows.net/assignment-1'
    CREDENTIALS = (AZURE_SAS_TOKEN = 'sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2025-08-25T03:31:43Z&st=2025-08-20T19:16:43Z&spr=https&sig=P1Wf7Itd2ivLkbx0grUdKFCh%2BPVqBAL6ev1%2FXRsAahk%3D');

CREATE OR REPLACE EXTERNAL TABLE ex_table_youtube_trending (VIDEO_ID VARCHAR AS (VALUE:c1::VARCHAR),
TITLE VARCHAR AS (VALUE:c2::VARCHAR),
PUBLISHEDAT DATE AS (VALUE:c3::DATE),
CHANNELID VARCHAR AS (VALUE:c4::VARCHAR),
CHANNELTITLE VARCHAR AS (VALUE:c5::VARCHAR),
CATEGORYID SMALLINT AS (VALUE:c6::SMALLINT),
TRENDING_DATE DATE AS (VALUE:c7::DATE),
VIEW_COUNT INT AS (VALUE:c8::INT),
LIKES INT AS (VALUE:c9::INT),
DISLIKES INT AS (VALUE:c10::INT),
COMMENT_COUNT INT AS (VALUE:c11::INT)
)
WITH LOCATION = @ASSIGNMENT_1.PUBLIC.STAGE_ASSIGNMENT
FILE_FORMAT=(TYPE='CSV' SKIP_HEADER = 1 
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY='"')
PATTERN='.*[.]csv';

CREATE OR REPLACE TABLE table_youtube_trending AS (SELECT 
VIDEO_ID,
TITLE,
PUBLISHEDAT,
CHANNELID,
CHANNELTITLE,
CATEGORYID,
TRENDING_DATE,
VIEW_COUNT,
LIKES,
DISLIKES,
COMMENT_COUNT,
SPLIT_PART(METADATA$FILENAME,'_',1)::VARCHAR AS COUNTRY
FROM ex_table_youtube_trending);



CREATE OR REPLACE EXTERNAL TABLE ex_table_youtube_category
WITH LOCATION = @ASSIGNMENT_1.PUBLIC.STAGE_ASSIGNMENT
FILE_FORMAT = (TYPE='JSON')
PATTERN = '.*[.]json';

CREATE OR REPLACE TABLE table_youtube_category AS 
SELECT SPLIT_PART(METADATA$FILENAME,'_',1)::VARCHAR AS COUNTRY,
b.VALUE:"id"::SMALLINT AS CATEGORYID,
b.VALUE:"snippet":"title"::VARCHAR AS CATEGORY_TITLE 
FROM ex_table_youtube_category a,
LATERAL FLATTEN(INPUT=>a.VALUE:"items") b;

CREATE OR REPLACE TABLE table_youtube_final AS 
SELECT UUID_STRING() AS ID,* FROM table_youtube_trending
LEFT OUTER JOIN table_youtube_category
USING (COUNTRY,CATEGORYID);


