-- Strategy: the accessibilty approach  --
SELECT DISTINCT CATEGORY_TITLE,
COUNT(DISTINCT VIDEO_ID)OVER (PARTITION BY CATEGORY_TITLE) AS TOTAL_VIDEO FROM table_youtube_final
WHERE CATEGORY_TITLE NOT IN ('Entertainment','Music','29')
ORDER BY TOTAL_VIDEO DESC;


SELECT DISTINCT CATEGORY_TITLE,
ROUND(AVG(TOTAL_VIDEO_PER_CHANNEL) OVER(PARTITION BY CATEGORY_TITLE),1) AS AVG_VIDEO_PER_CATEGORY,
ROUND(MEDIAN(TOTAL_VIDEO_PER_CHANNEL) OVER(PARTITION BY CATEGORY_TITLE),1)AS MEDIAN_VIDEO_PER_CATEGORY,
AVG_VIDEO_PER_CATEGORY-MEDIAN_VIDEO_PER_CATEGORY AS AVG_MEDIAN_DIFF
FROM (SELECT DISTINCT CATEGORY_TITLE,CHANNELTITLE,
COUNT(DISTINCT VIDEO_ID) OVER (PARTITION BY CHANNELID) AS TOTAL_VIDEO_PER_CHANNEL 
FROM table_youtube_final
)
WHERE CATEGORY_TITLE NOT IN ('Entertainment','Music','29')
ORDER BY AVG_MEDIAN_DIFF ASC;

WITH t1 AS (SELECT *,
RANK() OVER (PARTITION BY COUNTRY ORDER BY TOTAL_VIDEO DESC) AS RANK_BY_TOTAL_VIDEO
FROM(
SELECT DISTINCT COUNTRY,
CATEGORY_TITLE,
COUNT(DISTINCT VIDEO_ID)OVER (PARTITION BY (COUNTRY,CATEGORY_TITLE)) AS TOTAL_VIDEO 
FROM table_youtube_final
WHERE CATEGORY_TITLE NOT IN ('Entertainment','Music','29')
))
SELECT * EXCLUDE TOTAL_VIDEO FROM t1 WHERE CATEGORY_TITLE = 'People & Blogs';




