-- Q1 --
WITH t1 AS (SELECT *,RANK() OVER(PARTITION BY COUNTRY ORDER BY VIEW_COUNT DESC) AS RANK FROM table_youtube_final 
WHERE TRENDING_DATE = '2024-04-01' AND CATEGORY_TITLE='Gaming')
SELECT COUNTRY,TITLE,PUBLISHEDAT, CHANNELTITLE,VIEW_COUNT,RANK FROM t1 WHERE RANK <=3
;

-- Q2 --
SELECT COUNTRY, COUNT(DISTINCT COUNTRY, VIDEO_ID) AS CT FROM table_youtube_final
WHERE CONTAINS(COLLATE(TITLE,'en-ci'),'bts')
GROUP BY COUNTRY
ORDER BY CT DESC;

-- Q3 -- 
SELECT * EXCLUDE RANK FROM (
SELECT COUNTRY,TITLE,CHANNELTITLE,CATEGORY_TITLE,VIEW_COUNT,
ROUND(100*DIV0NULL(LIKES,VIEW_COUNT),2) AS LIKES_RATIO,
DATE_TRUNC('MONTH',TRENDING_DATE) AS YEAR_MONTH,
RANK() OVER(PARTITION BY (COUNTRY,YEAR_MONTH) ORDER BY VIEW_COUNT DESC) AS RANK 
FROM table_youtube_final WHERE YEAR(YEAR_MONTH)=2024
) WHERE RANK =1 ORDER BY (YEAR_MONTH,COUNTRY);

-- Q4 --
SELECT * EXCLUDE RANK FROM (
SELECT *,RANK() OVER(PARTITION BY COUNTRY ORDER BY TOTAL_CATEGORY_VIDEO DESC) AS RANK 
FROM (
SELECT DISTINCT COUNTRY,CATEGORY_TITLE,
COUNT(DISTINCT VIDEO_ID) OVER (PARTITION BY (COUNTRY,CATEGORY_TITLE)) AS TOTAL_CATEGORY_VIDEO,
COUNT(DISTINCT VIDEO_ID) OVER (PARTITION BY COUNTRY) AS TOTAL_COUNTRY_VIDEO,
ROUND(100*DIV0NULL(TOTAL_CATEGORY_VIDEO,TOTAL_COUNTRY_VIDEO),2) AS PERCENTAGE
FROM table_youtube_final WHERE YEAR(PUBLISHEDAT)=2022
))
WHERE RANK = 1
ORDER BY CATEGORY_TITLE,COUNTRY;

-- Q5 --
SELECT DISTINCT CHANNELTITLE, 
COUNT(DISTINCT VIDEO_ID) OVER(PARTITION BY CHANNELTITLE) AS TOTAL_CHANNEL_VIDEO 
FROM table_youtube_final
ORDER BY TOTAL_CHANNEL_VIDEO DESC
LIMIT 1;

